Use Pydantic's BaseSettings for project configuration #124
nsidnev/fastapi-realworld-example-app pull request #219
Opened 2021-11-01 15:31 UTC by samuelfirst

2021-11-03 05:01 UTC, nsidnev requested changes
@samuelfirst thanks so much for this PR! There are a few changes that need to be fixed before this can be merged. Could you take a look at the comments?

2021-11-03 05:08 UTC, nsidnev requested changes

2021-11-03 05:08 UTC, nsidnev commented on app/core/settings/app.py
> +    database_url: PostgresDsn
I think this also needs to be changed in the GitHub Actions workflow files so that they complete successfully.

2021-11-03 15:03 UTC, samuelfirst commented on README.rst
> +    echo APP_ENC=dev
Missed this typo(

2021-11-03 15:04 UTC, samuelfirst commented on app/api/dependencies/authentication.py
> +        username = jwt.get_username_from_token(token, str(settings.secret_key))
You are right!)

2021-11-03 15:04 UTC, samuelfirst commented on app/core/config.py
> +def get_app_settings() -> AppSettings:
`@lru_cache` was here but for some reason I removed it and forgot to return. I'll add `@cache`

2021-11-03 15:04 UTC, samuelfirst commented on app/core/settings/production.py
> +class ProdAppSettings(AppSettings):
Yep, I can)

2021-11-03 15:05 UTC, samuelfirst commented on app/core/settings/test.py
> +    secret_key: str = "test_secret"
I'll change it to `secret_key: SecretStr = SecretStr("test_secret")`

2021-11-03 15:06 UTC, samuelfirst commented on app/core/settings/app.py
> +    @validator("allowed_host", pre=True, check_fields=False)
Just one more typo.

2021-11-04 07:01 UTC, nsidnev approved these changes

2021-11-04 07:01 UTC, merged

2021-11-04 07:02 UTC, nsidnev commented
Thanks!